prune-blockchain=1

log-file=/home/Desktop/stressnet/monerod.log

rpc-bind-ip=127.0.0.1
rpc-bind-port=28081

rpc-restricted-bind-ip=0.0.0.0 
rpc-restricted-bind-port=28089

p2p-bind-port=28080

sync-pruned-blocks=1

data-dir=/home/Desktop/stressnet/blockchain


zmq-rpc-bind-port=28082


public-node=1

testnet=1

out-peers=12
in-peers=24

limit-rate-up=3072
limit-rate-down=3072


db-sync-mode=fast:async



start-mining=
mining-threads=1


# log-level=1

